name: swipe_photos
description: "Flutter project to swipe photos given list of image URLs."
publish_to: 'none'
version: 1.0
environment:
  sdk: '>=3.3.1 <4.0.0'
dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  photo_view: ^0.14.0
  flutter_svg: ^0.21.0-nullsafety.0
  cached_network_image: ^3.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/gallery1.jpg
    - assets/gallery2.jpg
    - assets/gallery3.jpg
    - assets/firefox.svg
